jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  oast-frontend-docker:
    machine: true
    steps:
      - checkout

      - run: |
          npm install
          docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-docker-report.json --severity high || true

      - store_artifacts:
          path: retirejs-docker-report.json
          destination: retirejs-docker-artifact
          when: always
          
  oast-frontend-npm:
    docker:
      - image: node:alpine3.10
    machine: true
    steps:
      - checkout

      - run: |
          npm install
          npm install -g retire
          retire --outputformat json --outputpath retirejs-npm-report.json --severity high

      - store_artifacts:
          path: retirejs-npm-report.json
          destination: retirejs-npm-artifact
          when: always

  sast:
    machine: true
    steps:
      - checkout

      - run: docker run --rm -v $(pwd):/src hysnsec/bandit -r /src -f json -o /src/bandit-report.json || true

      - store_artifacts:
          path: bandit-report.json
          destination: bandit-artifact
          when: always

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail           # Even if the job fails, continue to the next stage  
  zap_baseline:
    machine: true
    steps:
      - checkout

      - run: |
          docker pull owasp/zap2docker-stable:2.10.0
          docker run --user root --rm -v $(pwd):/zap/wrk:rw -w /zap owasp/zap2docker-stable:2.10.0 zap-baseline.py -t ${PROD_URL} -J zap-output.json

      - store_artifacts:
          path: zap-output.json
          destination: zap-artifact

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - oast-frontend-docker:
          requires:
            - test
      - oast-frontend-npm:
          requires:
            - test
      - sast:
          requires:
            - test
      - zap_baseline:
          requires:
            - sast
      - prod:
          type: approval
          requires:
            - integration
