jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  oast-frontend-doker:
    machine: true
    steps:
      - checkout

      - run: |
          docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-docker-report.json --severity high || true

      - store_artifacts:
          path: retirejs-docker-output.json
          destination: retirejs-artifact
          when: always
          
  oast-frontend-npm:
    docker:
      - image: node:alpine3.10
    machine: true
    steps:
      - checkout

      - run: |
          npm install
          npm install -g retire
          retire --outputformat json --outputpath retirejs-report.json --severity high

      - store_artifacts:
          path: retirejs-output.json
          destination: retirejs-artifact
          when: always

  sast:
    machine: true
    steps:
      - checkout

      - run: docker run --rm -v $(pwd):/src hysnsec/bandit -r /src -f json -o /src/bandit-output.json || true

      - store_artifacts:
          path: bandit-output.json
          destination: bandit-artifact
          when: always

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail           # Even if the job fails, continue to the next stages

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - oast-frontend-docker:
          requires:
            - test
      - oast-frontend-npm:
          requires:
            - test
      - sast:
          requires:
            - oast-frontend
      - integration:
          requires:
            - sast
      - prod:
          type: approval
          requires:
            - integration
